definitions:
  controller.errorResponse:
    properties:
      error:
        type: string
      status_code:
        type: integer
    type: object
info:
  contact: {}
  description: Aquila DB
  title: Aquila DB
  version: "1.0"
paths:
  /customer:
    get:
      description: Get customer
      responses: {}
      summary: Get customer
      tags:
      - Get customer
    patch:
      description: Create permanent customer
      responses: {}
      summary: Create permanent customer
      tags:
      - create permanent customer
    post:
      description: Create temp customer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controller.errorResponse'
      summary: Create temp customer
      tags:
      - create temp customer
swagger: "2.0"
